[metadata]
name = "dfint localization hook"

[settings]
# trace - 0, debug - 1, info - 2, error - 4
log_level = 0
log_file = "./dfint-data/dfint-log.log"
enable_search = true
enable_translation = true
watchdog = true
