[metadata]
name = "dfint localization hook offsets"
version = "50.11 classic win64"
checksum = 0x65190584

[offsets]
string_copy_n = 0xBAB0
string_append_n = 0xBBF0
addst = 0x7FADE0
addst_top = 0x7FAEC0
addst_flag = 0x7FAB50
standardstringentry = 0x9006C0
simplify_string = 0x3BB240
upper_case_string = 0x3BB580
lower_case_string = 0x3BB3E0
capitalize_string_words = 0x3BB720
capitalize_string_first_word = 0x3BB9A0
