[metadata]
name = "dfint localization hook offsets"
version = "50.13 steam win64"
checksum = 0x6625635E

[offsets]
string_copy_n = 0xD550
string_append_n = 0xD690
std_string_ctor = 0x1AA90
addst = 0x820C00
addst_top = 0x820CE0
addst_flag = 0x820B10
standardstringentry = 0x9275D0
simplify_string = 0x3DBE30
upper_case_string = 0x3DC170
lower_case_string = 0x3DBFD0
capitalize_string_words = 0x3DC310
capitalize_string_first_word = 0x3DC590
