[metadata]
name = "dfint localization hook offsets"
version = "50.12 steam win64"
checksum = 0x65E8286D

[offsets]
string_copy_n = 0xD550
string_append_n = 0xD690
std_string_ctor = 0x1AA90
addst = 0x81A970
addst_top = 0x81AA50
addst_flag = 0x81A880
standardstringentry = 0x9212C0
simplify_string = 0x3DA250
upper_case_string = 0x3DA590
lower_case_string = 0x3DA3F0
capitalize_string_words = 0x3DA730
capitalize_string_first_word = 0x3DA9B0
