[metadata]
name = "dfint localization hook offsets"
version = "50.11 steam win64"
checksum = 0x6518F842

[offsets]
string_copy_n = 0xBB30
string_append_n = 0xBC70
addst = 0x801DF0
addst_top = 0x801ED0
addst_flag = 0x801B60
standardstringentry = 0x907C20
simplify_string = 0x3C2140
upper_case_string = 0x3C2480
lower_case_string = 0x3C22E0
capitalize_string_words = 0x3C2620
capitalize_string_first_word = 0x3C28A0
