[metadata]
name = "dfint localization hook offsets"
version = "50.13 classic win64"
checksum = 0x66257238

[offsets]
string_copy_n = 0xD4E0
string_append_n = 0xD620
std_string_ctor = 0x1AA20
addst = 0x819C50
addst_top = 0x819D30
addst_flag = 0x819B60
standardstringentry = 0x91FFA0
simplify_string = 0x3D4F60
upper_case_string = 0x3D52A0
lower_case_string = 0x3D5100
capitalize_string_words = 0x3D5440
capitalize_string_first_word = 0x3D56C0
