[metadata]
name = "dfint localization hook offsets"
version = "50.13 itch.io win64"
checksum = 0x66256BBD

[offsets]
string_copy_n = 0xD4E0
string_append_n = 0xD620
std_string_ctor = 0x1AA20
addst = 0x81E2D0
addst_top = 0x81E3B0
addst_flag = 0x81E1E0
standardstringentry = 0x924CA0
simplify_string = 0x3D95A0
upper_case_string = 0x3D98E0
lower_case_string = 0x3D9740
capitalize_string_words = 0x3D9A80
capitalize_string_first_word = 0x3D9D00
