[metadata]
name = "dfint localization hook offsets"
version = "50.14 steam win64"
checksum = 0x66D87E02

[offsets]
string_copy_n = 0xD510
string_append_n = 0xD650
std_string_ctor = 0x1A930
addst = 0x85F930
addst_top = 0x85FA10
addst_flag = 0x85F840
standardstringentry = 0x96AE30
simplify_string = 0x40D050
upper_case_string = 0x40D390
lower_case_string = 0x40D1F0
capitalize_string_words = 0x40D530
capitalize_string_first_word = 0x40D7C0