[metadata]
name = "dfint localization hook offsets"
version = "50.10 itch.io win64"
checksum = 0x6507C6DE

[offsets]
string_copy_n = 0xBA50
string_append_n = 0xBB90
addst = 0x7FE8C0
addst_top = 0x7FE9A0
addst_flag = 0x7FE630
standardstringentry = 0x904760
simplify_string = 0x3BF780
upper_case_string = 0x3BFAC0
lower_case_string = 0x3BF920
capitalize_string_words = 0x3BFC60
capitalize_string_first_word = 0x3BFEE0
