[metadata]
name = "dfint localization hook offsets"
version = "50.15 itch.io win64"
checksum = 0x6759DDCE

[offsets]
string_copy_n = 0xD4D0
string_append_n = 0xD610
std_string_ctor = 0x1A8F0
addst = 0x84E160
addst_top = 0x84E240
addst_flag = 0x84E070
standardstringentry = 0x959310
simplify_string = 0x3FD050
upper_case_string = 0x3FD390
lower_case_string = 0x3FD1F0
capitalize_string_words = 0x3FD530
capitalize_string_first_word = 0x3FD7C0