[metadata]
name = "dfint localization hook offsets"
version = "50.11 itch.io win64"
checksum = 0x6518FC3A

[offsets]
string_copy_n = 0xBAB0
string_append_n = 0xBBF0
addst = 0x7FF480
addst_top = 0x7FF560
addst_flag = 0x7FF1F0
standardstringentry = 0x9052B0
simplify_string = 0x3BF8B0
upper_case_string = 0x3BFBF0
lower_case_string = 0x3BFA50
capitalize_string_words = 0x3BFD90
capitalize_string_first_word = 0x3C0010
