[metadata]
name = "dfint localization hook offsets"
version = "50.14 classic win64"
checksum = 0x66D86DE9

[offsets]
string_copy_n = 0xD4A0
string_append_n = 0xD5E0
std_string_ctor = 0x1A8C0
addst = 0x8587E0
addst_top = 0x8588C0
addst_flag = 0x8586F0
standardstringentry = 0x9634D0
simplify_string = 0x406180
upper_case_string = 0x4064C0
lower_case_string = 0x406320
capitalize_string_words = 0x406660
capitalize_string_first_word = 0x4068F0