[metadata]
name = "dfint localization hook offsets"
version = "50.10 classic win64"
checksum = 0x6507D1C4

[offsets]
string_copy_n = 0xBA50
string_append_n = 0xBB90
addst = 0x7FA1C0
addst_top = 0x7FA2A0
addst_flag = 0x7F9F30
standardstringentry = 0x8FFA20
simplify_string = 0x3BB0B0
upper_case_string = 0x3BB3F0
lower_case_string = 0x3BB250
capitalize_string_words = 0x3BB590
capitalize_string_first_word = 0x3BB810
