[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta23 steam win64"
checksum = 0x66FAF9FE

[offsets]
string_copy_n = 0x1F820
string_append_n = 0x1F960
std_string_ctor = 0x2CC80
addst = 0x9EC310
addst_top = 0x9EC3F0
addst_flag = 0x9EC220
standardstringentry = 0xB001F0
simplify_string = 0x49E6C0
upper_case_string = 0x49EA00
lower_case_string = 0x49E860
capitalize_string_words = 0x49EBA0
capitalize_string_first_word = 0x49EE30