[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta28 steam win64"
checksum = 0x677E4951

[offsets]
string_copy_n = 0x20020
string_append_n = 0x20160
std_string_ctor = 0x2D490
addst = 0xA01E60
addst_top = 0xA01F40
addst_flag = 0xA01D70
standardstringentry = 0xB24C00
simplify_string = 0x4A4250
upper_case_string = 0x4A4590
lower_case_string = 0x4A43F0
capitalize_string_words = 0x4A4730
capitalize_string_first_word = 0x4A49C0