[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta26 steam win64"
checksum = 0x674700BB

[offsets]
string_copy_n = 0x20140
string_append_n = 0x20280
std_string_ctor = 0x2D5A0
addst = 0x9EFC60
addst_top = 0x9EFD40
addst_flag = 0x9EFB70
standardstringentry = 0xB0E370
simplify_string = 0x49D800
upper_case_string = 0x49DB40
lower_case_string = 0x49D9A0
capitalize_string_words = 0x49DCE0
capitalize_string_first_word = 0x49DF70