[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta25 steam win64"
checksum = 0x671A853A

[offsets]
string_copy_n = 0x1F840
string_append_n = 0x1F980
std_string_ctor = 0x2CCB0
addst = 0x9DD2A0
addst_top = 0x9DD380
addst_flag = 0x9DD1B0
standardstringentry = 0xAF34D0
simplify_string = 0x493610
upper_case_string = 0x493950
lower_case_string = 0x4937B0
capitalize_string_words = 0x493AF0
capitalize_string_first_word = 0x493D80