[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta27 steam win64"
checksum = 0x674DD2E2

[offsets]
string_copy_n = 0x20140
string_append_n = 0x20280
std_string_ctor = 0x2D5A0
addst = 0x9EFD80
addst_top = 0x9EFE60
addst_flag = 0x9EFC90
standardstringentry = 0xB0E490
simplify_string = 0x49D850
upper_case_string = 0x49DB90
lower_case_string = 0x49D9F0
capitalize_string_words = 0x49DD30
capitalize_string_first_word = 0x49DFC0